#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_CONTROL_PERIOD_MS 10u
#define APP_SYSTEM_CORE_CLOCK_HZ 80000000u

#define APP_WHEEL_BASE_CM 12.0f
#define APP_MAX_SPEED_CM_S 55.0f
#define APP_MIN_FORWARD_CM_S 0.0f
#define APP_CRUISE_SPEED_CM_S 38.0f
#define APP_ARC_SPEED_CM_S 30.0f

#define APP_STRAIGHT_AB_CM 100.0f
#define APP_STRAIGHT_CD_CM 100.0f
#define APP_ARC_RADIUS_CM 40.0f
#define APP_ARC_HALF_CM 125.66f
#define APP_DIAGONAL_AC_CM 128.06f
#define APP_DIAGONAL_BD_CM 128.06f

#define APP_DISTANCE_DONE_TOLERANCE_CM 1.0f
#define APP_WAYPOINT_ALERT_MS 180u

#define APP_LINE_SENSOR_COUNT 4u
#define APP_LINE_BLACK_READING 1000u
#define APP_LINE_ACTIVE_THRESHOLD 500u

#define APP_ENCODER_TICKS_PER_CM 12.0f
#define APP_ALLOW_REVERSE 0

#define APP_STRAIGHT_KP 0.95f
#define APP_STRAIGHT_KI 0.00f
#define APP_STRAIGHT_KD 0.08f

#define APP_LINE_KP 8.0f
#define APP_LINE_KI 0.00f
#define APP_LINE_KD 1.2f

#define APP_LEFT_MOTOR_KP 50.0f
#define APP_LEFT_MOTOR_KI 10.0f
#define APP_RIGHT_MOTOR_KP 50.0f
#define APP_RIGHT_MOTOR_KI 10.0f

#define APP_PWM_LIMIT 255
#define APP_LEFT_FWD_DEADZONE 30
#define APP_LEFT_REV_DEADZONE 38
#define APP_RIGHT_FWD_DEADZONE 29
#define APP_RIGHT_REV_DEADZONE 23

#define APP_MPU6050_ADDR 0x68u
#define APP_MPU6050_GYRO_ZOUT_H 0x47u
#define APP_MPU6050_GYRO_LSB_PER_DPS 131.0f
#define APP_GYRO_STATIC_FILTER_DPS 0.5f
#define APP_GYRO_CALIBRATION_SAMPLES 100u

#endif
